name: rag-from-scratch

services:
  jupyter:
    container_name: rag-jupyter
    env_file: .env
    build:
        context: jupyter/
    networks:
        - internal
    ports:
      - "127.0.0.1:8888:8888"  # jupyter notebook on http://localhost:8888/
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    # On localhost, no need to authenticate.
    command: start-notebook.sh --IdentityProvider.token=''

  postgres:
    container_name: rag-postgres
    environment:
      POSTGRES_DB: rag
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
    build:
        context: postgres/
    networks:
        - internal
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

networks:
    internal:
        driver: bridge